import Foundation

/// 問題ごとの「選択肢ごとの解説」と「仕様書の参照先」
struct QuizNote {
    let id: String
    /// choices と同じ順番。正解の選択肢は空文字（本文の解説で説明する）
    let choices: [String]
    let spec: SpecRef
}

enum QuizNotes {
    static let byID: [String: QuizNote] = Dictionary(
        (beginner + intermediate + advanced + latest).map { ($0.id, $0) },
        uniquingKeysWith: { first, _ in first })

    /// 仕様書は PCIe Base Specification 7.1 のページ番号
    static func n(_ id: String, _ choices: [String], _ section: String, _ title: String, _ page: Int) -> QuizNote {
        QuizNote(id: id, choices: choices, spec: SpecRef(section: section, title: title, page: page))
    }

    // MARK: - 入門（1〜4章）

    static let beginner: [QuizNote] = [
        // 1. PCIeとは
        n("intro-1", ["送信用だけでは受信ができません。レーンは送受信のペアで1組です。", "",
                      "PCIeはシングルエンドではなく差動信号です。", "32本のパラレル線は旧PCIのバスの特徴です。"],
          "1.2", "PCI Express Link", 148),
        n("intro-2", ["これはPCIeの特徴です（1本のリンクは2つのポートだけを結ぶ）。", "これもPCIeの特徴です。送信と受信が別の線なので同時に通信できます。",
                      "", "これもPCIeの特徴です（受信側がデータからクロックを再生する）。"],
          "1.1", "An Evolving I/O Interconnect", 147),
        n("intro-3", ["符号化後の実データ速度ではありません。符号化のオーバーヘッドを含んだ生の値です。", "",
                      "パケットの数ではなく、ビットを送る回数です。", "1レーン・片方向あたりの値です。双方向の合計ではありません。"],
          "1.2", "PCI Express Link", 148),
        n("intro-4", ["JEDECはDRAMなどのメモリの規格団体です。", "USB-IFはUSBの規格団体です。", "",
                      "IEEEはEthernet（802.3）などの規格団体です。"],
          "1.1", "An Evolving I/O Interconnect", 147),
        n("intro-5", ["8はレーン数です。1レーンに2ペアあります。", "", "32は信号線の本数です（16ペア × 2本）。", "64は多すぎます。"],
          "1.2", "PCI Express Link", 148),
        n("intro-6", ["x1は規定されています。", "x4は規定されています。", "x16は規定されています。", ""],
          "1.2", "PCI Express Link", 148),
        n("intro-7", ["", "LFSRはスクランブルなどに使う、疑似乱数を作る回路です。",
                      "FECは誤りを訂正する符号です。", "ECAMはコンフィグ空間にアクセスする仕組みです。"],
          "1.2", "PCI Express Link", 148),
        n("intro-8", ["2.5 Gbit/sは1レーン分です。8レーンを掛けます。", "16 Gbit/sは8b/10bを除いたあとの値です。",
                      "", "40 Gbit/sは双方向の合計です。"],
          "1.2", "PCI Express Link", 148),
        n("intro-9", ["シングルエンドはノイズに弱く、PCIeでは使いません。", "",
                      "光で延長する方式（Optical Aware Retimer）もありますが、基本は電気の差動信号です。", "電流ループは産業用の信号方式です。"],
          "1.2", "PCI Express Link", 148),
        n("intro-10", ["USBとはソフトウェアの仕組みが違います。", "SATAとはソフトウェアの仕組みが違います。", "",
                       "Ethernetとはソフトウェアの仕組みが違います。"],
          "1.4", "Hardware/Software Model for Discovery, Configuration and Operation", 154),
        n("intro-11", ["", "クロックの倍率ではありません。", "世代はGen4やPCIe 4.0と書きます。", "デバイスの数ではありません。"],
          "1.2", "PCI Express Link", 148),
        n("intro-12", ["時間で切り替えるのは半二重です。", "", "PCIeは両方向に送れます。",
                       "クロックはデータに埋め込まれていて、受信側が再生します。"],
          "1.2", "PCI Express Link", 148),
        n("intro-13", ["", "消費電力はゼロになりません。", "クロックを取り出しやすくするため、符号化やスクランブルはむしろ必要です。",
                       "レーン数とは関係ありません。"],
          "1.2", "PCI Express Link", 148),
        n("intro-14", ["小さいカードは大きいスロットに挿せます（逆は挿せません）。", "",
                       "カード側にレーンが1本しかないので、x16にはなりません。", "故障しません。リンク幅は自動で決まります。"],
          "4.2.5.11", "Link Width and Lane Sequence Negotiation", 535),

        // 2. トポロジ
        n("topo-1", ["3ビットはFunction番号です。", "", "8ビットはBus番号です。", "16ビットはBDF全体です。"],
          "2.2.4", "Routing and Addressing Rules", 195),
        n("topo-2", ["Endpointはツリーの末端にあるデバイスです。", "Switchはパケットを中継する装置です。", "",
                     "Retimerは信号を受け直して中継する部品です。"],
          "1.3.1", "Root Complex", 150),
        n("topo-3", ["8はARIなしの上限です。", "32はDevice番号の数です。", "", "4096はシーケンス番号の数（12ビット）などで、Functionの数ではありません。"],
          "6.13", "Alternative Routing-ID Interpretation (ARI)", 900),
        n("topo-4", ["スイッチはEndpointとしては見えません。", "",
                     "Root Complexとは別の部品です。", "ソフトウェアから見えて、列挙の対象になります。"],
          "1.3.3", "Switch", 153),
        n("topo-5", ["3はBus番号です。", "7はFunction番号です。", "15は16進の0fです。1fは31です。", ""],
          "2.2.4", "Routing and Addressing Rules", 195),
        n("topo-6", ["アップストリームはCPUに近づく方向です。", "", "ピアツーピアはデバイス同士の通信のことです。",
                     "ブロードキャストは一斉送信のことです。"],
          "1.3", "PCI Express Fabric Topology", 149),
        n("topo-7", ["スイッチの下にあるのは普通のEndpointです。", "", "RCiEPはEndpointで、ブリッジではありません。",
                     "Retimerとは関係ありません。"],
          "1.3.2", "Endpoints", 151),
        n("topo-8", ["リンクの両端には必ずポートがあるので、1つにはなりません。", "",
                     "複数のデバイスをつなぐのは旧PCIの共有バスです。", "32はDevice番号の数です。"],
          "1.2", "PCI Express Link", 148),
        n("topo-9", ["アップストリームポートがないと、上流につながれません。", "",
                     "2つ以上は持ちません。", "ダウンストリームポートは複数ありますが、アップストリームは1つです。"],
          "1.3.3", "Switch", 153),
        n("topo-10", ["3ビットはFunction番号です。", "5ビットはDevice番号です。", "", "16ビットはBDF全体です。"],
          "2.2.4", "Routing and Addressing Rules", 195),
        n("topo-11", ["", "Type 1ヘッダのBARは自分のレジスタ領域用です。", "Command/Statusは動作の制御と状態です。",
                      "Vendor ID/Device IDはデバイスの識別です。"],
          "7.5.1.3", "Type 1 Configuration Space Header", 1130),
        n("topo-12", ["", "32台つなげたのは旧PCIの共有バスです。", "8はFunction数の上限です。", "256はARIを使ったときのFunction数です。"],
          "7.3.1", "Device Number", 1105),
        n("topo-13", ["32はDevice番号の数です。", "128では足りません。Bus番号は8ビットです。", "",
                      "4096にはなりません。Bus番号は8ビットなので256個までです。"],
          "7.2.2", "PCI Express Enhanced Configuration Access Mechanism (ECAM)", 1100),
        n("topo-14", ["", "Root PortはEndpointではありません。", "メモリコントローラはRoot Complexの内部の部品です。",
                      "スイッチの部品ではなく、Root Complexのポートです。"],
          "1.3.1", "Root Complex", 150),
        n("topo-15", ["マルチファンクションデバイスなら2つ以上持てます。", "4ではありません。", "", "32はDevice番号の数です。"],
          "2.2.4", "Routing and Addressing Rules", 195),

        // 3. 世代と帯域
        n("gen-1", ["8b/10bはGen1とGen2の符号化です。", "64b/66bはEthernetなどで使う符号化です。", "",
                    "PAM4とFlitはGen6からです。"],
          "4.2.2", "128b/130b Encoding for 8.0 GT/s, 16.0 GT/s, and 32.0 GT/s Data Rates", 387),
        n("gen-2", ["約2 GB/sはGen4 x1の値です。", "約4 GB/sはGen3 x4の値です。", "", "約16 GB/sはGen4 x8の値です。"],
          "1.2", "PCI Express Link", 148),
        n("gen-3", ["50%ではありません。", "", "98.5%は128b/130bの効率です。", "100%は符号化のオーバーヘッドがない1b/1bです。"],
          "4.2.1", "8b/10b Encoding for 2.5 GT/s and 5.0 GT/s Data Rates", 379),
        n("gen-4", ["PCIeは後方互換なので動作します。", "", "スロット側が対応していないので、Gen5では動きません。",
                    "リンク幅は世代とは関係なく、両者に共通する幅になります。"],
          "4.2.5.10", "Link Data Rate Negotiation", 534),
        n("gen-5", ["1ビットではありません。", "", "8ビットではありません。", "10ビットは8b/10bの1シンボルの長さです。"],
          "4.2.2.1", "Lane Level Encoding", 388),
        n("gen-6", ["約32 GB/sはGen5 x8やGen4 x16の値です。", "", "約128 GB/sはGen6 x16の値です。", "約256 GB/sはGen7 x16の値です。"],
          "1.2", "PCI Express Link", 148),
        n("gen-7", ["", "128b/130bは8.0〜32.0 GT/sです。", "1b/1bは64.0 GT/s以上です。", "64b/66bはPCIeでは使いません。"],
          "4.2.1", "8b/10b Encoding for 2.5 GT/s and 5.0 GT/s Data Rates", 379),
        n("gen-8", ["すべてのポートに必須なのはNon-Flit Modeのほうです。", "16.0 GT/sでFlit Modeは必須ではありません。", "",
                    "リンク幅とは関係ありません。"],
          "4.2.3", "Flit Mode Operation", 408),
        n("gen-9", ["約6.4 Gbit/sは8b/10b（効率80%）を当てはめたときの値です。", "",
                    "128b/130bの分だけ、8.0より少し下がります。", "10 Gbit/sは8.0を超えているのでありえません。"],
          "1.2", "PCI Express Link", 148),
        n("gen-10", ["1.25 GT/sではありません。", "", "5.0 GT/sはGen2です。", "8.0 GT/sはGen3です。"],
          "1.2", "PCI Express Link", 148),
        n("gen-11", ["8.0 GT/sはGen3です。", "", "32.0 GT/sはGen5です。", "64.0 GT/sはGen6です。"],
          "1.2", "PCI Express Link", 148),
        n("gen-12", ["", "レーン数は変わっていません。", "PAM4はGen6からです。", "FECはGen6からです。"],
          "4.2.2", "128b/130b Encoding for 8.0 GT/s, 16.0 GT/s, and 32.0 GT/s Data Rates", 387),
        n("gen-13", ["", "Gen6の1b/1bは、Gen5の128b/130bと比べて効率が1.5%ほど上がるだけです。",
                     "レーン数は変わっていません。", "シンボルレート（クロック）は同じです。"],
          "4.2.3.1.1", "PAM4 Signaling", 411),
        n("gen-14", ["約2 GB/sはGen3 x2の値です。", "約8 GB/sはGen3 x8の値です。", "", "約32 GB/sはGen4 x16の値です。"],
          "1.2", "PCI Express Link", 148),
        n("gen-15", ["", "10倍ずつ上がってはいません。", "速度は世代ごとに上がっています。", "1.2倍では倍増とは言えません。"],
          "1.2", "PCI Express Link", 148),

        // 4. レイヤ構造
        n("layer-1", ["トランザクション層はTLPを作りますが、再送はしません。", "", "物理層は符号化やリンクの初期化を担当します。",
                      "PCIeの層にアプリケーション層はありません。"],
          "3.6.2", "LCRC, TLP Sequence Number, and Retry Management (TLP Transmitter)", 361),
        n("layer-2", ["", "DLLPは1本のリンクの両端だけでやりとりします。", "Ordered Setも1本のリンク内だけです。",
                      "スイッチを越えるのはTLPだけです。"],
          "1.5", "PCI Express Layering Overview", 155),
        n("layer-3", ["リンクごとに付け直されるのはLCRCです。", "end-to-endで保護するのはECRCです。", "",
                      "ECRCはトランザクション層、LCRCはデータリンク層が付けます。"],
          "2.7.1", "ECRC Rules", 321),
        n("layer-4", ["", "データリンク層はTLPを確実に届ける役目です。", "物理層はビットを送る役目です。",
                      "TLPはトランザクション層が作ります。"],
          "1.5.1", "Transaction Layer", 156),
        n("layer-5", ["トランザクション層にはありません。", "データリンク層にはありません。", "",
                      "電気サブブロックは送受信回路の部分で、状態機械は論理サブブロックにあります。"],
          "4.2.6", "Link Training and Status State Machine (LTSSM) Descriptions", 537),
        n("layer-6", ["8ビットではありません。", "", "32ビットはTLPのLCRCです。", "Non-Flit ModeのDLLPには必ずCRCが付きます。"],
          "3.5", "Data Link Layer Packets (DLLPs)", 349),
        n("layer-7", ["トランザクション層は、データリンク層が確認したTLPを受け取ります。", "",
                      "物理層はフレームを取り出すところまでです。", "ハードウェアが確認するので、ソフトウェアは関わりません。"],
          "3.6.3", "LCRC and TLP Sequence Number (TLP Receiver) (Non-Flit Mode)", 371),
        n("layer-8", ["", "下から上の順になっています。", "データリンク層はトランザクション層の下です。", "物理層が一番下です。"],
          "1.5", "PCI Express Layering Overview", 155),
        n("layer-9", ["ACK/NAKはDLLPの用途です（Non-Flit Mode）。", "UpdateFCなどはDLLPです。", "PM_Enter_L1などはDLLPです。", ""],
          "3.5", "Data Link Layer Packets (DLLPs)", 349),
        n("layer-10", ["", "スイッチを越えるのはTLPです。", "宛先によらず、リンク内で完結します。", "ACKもリンク内で完結します。"],
          "3.5", "Data Link Layer Packets (DLLPs)", 349),
        n("layer-11", ["", "必須ではありません。", "Gen6でも任意です。", "Memory Writeでも任意です。"],
          "2.7.1", "ECRC Rules", 321),
        n("layer-12", ["符号化は物理層の役割です。", "スクランブルは物理層の役割です。", "リンクトレーニング（LTSSM）は物理層の役割です。", ""],
          "1.5.3", "Physical Layer", 156),
        n("layer-13", ["トランザクション層はTLPを扱います。", "データリンク層はDLLPを扱います。", "", "PCIeの層にアプリケーション層はありません。"],
          "4.2.5.1", "Training Sequences", 494),
    ]
}
