import Foundation

extension QuizNotes {
    // MARK: - 上級（9〜12章）

    static let advanced: [QuizNote] = [
        // 9. LTSSM
        n("ltssm-1", ["", "最高速度へは、L0に着いたあとRecoveryを通って上げます。", "Gen3の速度から始まることはありません。",
                      "毎回同じ手順で、ランダムではありません。"],
          "4.2.7.2", "Polling", 553),
        n("ltssm-2", ["Detectは相手がつながっているかを調べる状態です。", "Pollingはビットやシンボルの同期と、極性の確認をする状態です。", "",
                      "Recoveryは速度変更や再同期をする状態です。"],
          "4.2.7.3", "Configuration", 564),
        n("ltssm-3", ["", "Pollingは、相手が見つかったあとにTS1/TS2を交換する状態です。", "L0sは省電力状態です。", "Loopbackは試験用の折り返し状態です。"],
          "4.2.7.1", "Detect", 551),
        n("ltssm-4", ["TS1はL1から戻るときなど、Recoveryで使います。", "", "SKPはクロックの差を吸収します。",
                      "EIOSはElectrical Idleに入るときに送ります。"],
          "4.2.7.6", "L0s", 621),
        n("ltssm-5", ["2 msはHot ResetからDetectに戻るタイムアウトです。", "", "24 msはPolling.Activeのタイムアウトです。",
                      "48 msはPolling.Configurationのタイムアウトです。"],
          "4.2.7.1", "Detect", 551),
        n("ltssm-6", ["8個は、受信側で連続して受け取る必要があるトレーニングシーケンスの数です。", "16個ではありません。", "",
                      "4096個ではありません。"],
          "4.2.7.2", "Polling", 553),
        n("ltssm-7", ["12 msはDetect.Quietのタイムアウトです。", "24 msはPolling.Activeのタイムアウトです。", "", "100 msではありません。"],
          "4.2.7.2", "Polling", 553),
        n("ltssm-8", ["", "12 msはDetect.Quietのタイムアウトです。", "24 msはPolling.Activeのタイムアウトです。",
                      "48 msはPolling.Configurationのタイムアウトです。"],
          "4.2.7.11", "Hot Reset", 637),
        n("ltssm-9", ["Polling.Complianceは試験のときに入る状態で、到達できます。", "", "Recovery.Speedは速度変更に使う状態で、到達できます。",
                      "Loopbackは試験用の状態で、到達できます。"],
          "4.2.7.2", "Polling", 553),
        n("ltssm-10", ["", "DL_Upはデータリンク層の状態です。", "Link Activeはデータリンク層の状態を示すレジスタのビットです。",
                       "REPLAY_NUMは再送回数のカウンタです。"],
          "4.2.7.3", "Configuration", 564),
        n("ltssm-11", ["Detectは主な状態の1つです。", "Pollingは主な状態の1つです。", "Configurationは主な状態の1つです。", ""],
          "4.2.6", "Link Training and Status State Machine (LTSSM) Descriptions", 537),
        n("ltssm-12", ["", "Detectは最初からやり直す状態で、通常の再調整では使いません。", "PollingはL0に着く前の状態です。",
                       "Disabledはソフトウェアがリンクを止めた状態です。"],
          "4.2.7.4", "Recovery", 585),
        n("ltssm-13", ["", "Polling.Complianceは試験用の状態です。", "Detect.Activeは相手の受信器を検出する状態です。",
                       "L1.EntryはL1に入るための状態です。"],
          "4.2.7.4", "Recovery", 585),
        n("ltssm-14", ["", "電力を下げる状態はL0sやL1です。", "エラーからの回復はRecoveryです。", "リンク幅はConfigurationで決めます。"],
          "4.2.7.2", "Polling", 553),
        n("ltssm-15", ["", "電力を下げる状態はL0sやL1です。", "リンクを止めるのはDisabledです。", "速度を変えるのはRecoveryです。"],
          "4.2.7.10", "Loopback", 628),
        n("ltssm-16", ["", "TS2はGen1のときから使われています。", "TS1はトレーニング用で、データは運びません。",
                       "役割が違います。TS2は次の状態に進む準備ができた合図です。"],
          "4.2.5.1", "Training Sequences", 494),

        // 10. コンフィグ空間
        n("cfg-1", ["64バイトはType 0/1の基本ヘッダの大きさです。", "256バイトはPCI互換の領域で、PCIeではこの後ろに拡張領域があります。", "",
                    "64KBではありません。"],
          "7.2.2", "PCI Express Enhanced Configuration Access Mechanism (ECAM)", 1100),
        n("cfg-2", ["0x00001000はFunction 1（Func<<12）のアドレスです。", "0x00008000はDevice 1（Dev<<15）のアドレスです。", "",
                    "0x01000000はBus 16のアドレスです。"],
          "7.2.2", "PCI Express Enhanced Configuration Access Mechanism (ECAM)", 1100),
        n("cfg-3", ["64KBならFFFF0000hが読めます。", "256KBならFFFC0000hが読めます。", "", "16MBならFF000000hが読めます。"],
          "7.5.1.2.1", "Base Address Registers (Offset 10h - 24h)", 1122),
        n("cfg-4", ["0000hは無効なVendor IDですが、存在しないときの値ではありません。", "", "8086hはIntelのVendor IDです。",
                    "止まらずにオール1が返るので、ソフトウェアは不在と判断できます。"],
          "7.3", "Configuration Transaction Rules", 1105),
        n("cfg-5", ["Type 0はEndpointのヘッダです。", "", "Type 2はCardBusブリッジ用で、PCIeでは使いません。", "Type 3はありません。"],
          "7.5.1.3", "Type 1 Configuration Space Header", 1130),
        n("cfg-6", ["4KBは1つのFunctionの大きさです。", "256KBではありません。", "", "256MBは256本のバスすべての大きさです。"],
          "7.2.2", "PCI Express Enhanced Configuration Access Mechanism (ECAM)", 1100),
        n("cfg-7", ["00h〜0ChはVendor IDやCommandなどの共通部分です。", "", "28h〜3ChにはSubsystem IDやCapabilities Pointerなどがあります。",
                    "100h以降は拡張コンフィグ空間です。"],
          "7.5.1.2.1", "Base Address Registers (Offset 10h - 24h)", 1122),
        n("cfg-8", ["0EhはHeader Typeです。", "10hはBAR0です。", "", "100hは拡張Capabilityの先頭です。"],
          "7.5.1.1.11", "Capabilities Pointer (Offset 34h)", 1120),
        n("cfg-9", ["ヘッダの種類はbit 6:0で示します。", "", "BISTの対応はBISTレジスタで示します。", "64ビットBARかどうかはBAR自身の下位ビットで示します。"],
          "7.5.1.1.9", "Header Type Register (Offset 0Eh)", 1118),
        n("cfg-10", ["18hはPrimary Bus Numberです。", "", "1AhはSubordinate Bus Numberです。", "1BhはSecondary Latency Timerです。"],
          "7.5.1.3.3", "Secondary Bus Number Register (Offset 19h)", 1132),
        n("cfg-11", ["", "02hはDevice IDです。", "04hはCommandです。", "08hはRevision IDです。"],
          "7.5.1.1.1", "Vendor ID Register (Offset 00h)", 1111),
        n("cfg-12", ["", "Bus Master Enableは、デバイスが自分からアクセスする（DMA）ためのビットです。",
                     "Interrupt DisableはINTxを止めるビットです。", "SERR# Enableはエラーの報告に関するビットです。"],
          "7.5.1.1.3", "Command Register (Offset 04h)", 1112),
        n("cfg-13", ["", "Memory Space Enableは、デバイスがアクセスを受け付けるためのビットです。",
                     "I/O Space EnableはI/O空間へのアクセスを受け付けるビットです。", "Parity Error Responseはエラー処理のビットです。"],
          "7.5.1.1.3", "Command Register (Offset 04h)", 1112),
        n("cfg-14", ["40h〜FFhは、PCI互換領域のCapabilityがよく置かれる場所です。", "", "FFhはPCI互換領域の最後のバイトです。",
                     "1000hは次のFunctionのコンフィグ空間（ECAM）です。"],
          "7.6", "PCI Express Extended Capabilities", 1208),
        n("cfg-15", ["1つは32ビットのBARです。", "", "3つではありません。", "6つはType 0ヘッダのBARの総数です。"],
          "7.5.1.2.1", "Base Address Registers (Offset 10h - 24h)", 1122),
        n("cfg-16", ["", "bit 15〜19はDevice番号です。", "bit 20〜27はBus番号です。", "bit 0〜11はレジスタのオフセットです。"],
          "7.2.2", "PCI Express Enhanced Configuration Access Mechanism (ECAM)", 1100),

        // 11. 割り込みと電源管理
        n("int-1", ["4はINTA〜INTDの数です。", "32はMSIの最大数です。", "256ではありません。", ""],
          "7.7.2", "MSI-X Capability and Table Structure", 1217),
        n("int-2", ["PCIeには割り込み専用の信号線がありません。", "", "DLLPは隣のポートとのやりとりで、割り込みには使いません。",
                    "Ordered Setは物理層の信号です。"],
          "6.1.4", "MSI and MSI-X Operation", 790),
        n("int-3", ["PMEは、デバイスがシステムに起床を求める仕組みです。", "", "LTRは許容できる遅延を通知する仕組みです。",
                    "D3coldは主電源が切れたデバイスの状態です。"],
          "5.4.1", "Active State Power Management (ASPM)", 753),
        n("int-4", ["D0は通常どおり動いている状態です。", "D1は浅い省電力状態です。", "",
                    "D3coldは主電源が切れているので、コンフィグ空間にアクセスできません。"],
          "5.3.1", "Device Power Management States (D-States) of a Function", 738),
        n("int-5", ["PCIeには割り込み専用の信号線がありません。", "", "MSIとは別の方式です。", "DLLPでは伝えません。"],
          "6.1.2", "PCI-compatible INTx Emulation", 790),
        n("int-6", ["Capabilityには、テーブルの場所（BARの番号とオフセット）だけが入っています。", "",
                    "ホストのメモリではなく、デバイスのBAR空間にあります。", "Root Complexの中ではありません。"],
          "7.7.2", "MSI-X Capability and Table Structure", 1217),
        n("int-7", ["PERST#はリセットの信号です。", "", "WAKE#はL2などから起こすときの信号です。", "PRSNT#はカードの挿入を検出する信号です。"],
          "5.5", "L1 PM Substates", 770),
        n("int-8", ["", "L1はFlit Modeでも使えます。", "L1.2はFlit Modeでも使えます。", "L0pはFlit Modeで使う省電力状態です。"],
          "4.2.6.7", "L0p Overview", 539),
        n("int-9", ["ASPMはリンクを自動で省電力状態にする仕組みです。", "", "PMEは起床を求める仕組みです。",
                    "OBFFは、プラットフォームの都合のよい時間帯をデバイスに知らせる仕組みです。"],
          "6.18", "Latency Tolerance Reporting (LTR) Mechanism", 918),
        n("int-10", ["1は最小の数です。", "8ではありません。", "", "2048はMSI-Xの最大数です。"],
          "7.7.1", "MSI Capability Structures", 1209),
        n("int-11", ["", "1ベクタしか使えないわけではありません。", "INTxは使いません。", "MSI-Xのテーブルはコンフィグ空間ではなくBAR空間にあります。"],
          "7.7.2", "MSI-X Capability and Table Structure", 1217),
        n("int-12", ["", "動いている状態はD0です。", "電源が入ったまま止めた状態はD3hotです。", "L0はリンクの状態です。"],
          "5.3.1", "Device Power Management States (D-States) of a Function", 738),
        n("int-13", ["", "L2/L3はソフトウェアが電源を落とすときの状態です。", "D0/D3はデバイスの状態です。",
                     "Detect/Pollingはリンクの初期化の状態です。"],
          "5.4.1", "Active State Power Management (ASPM)", 753),
        n("int-14", ["", "L0.1やL0.2という状態はありません。", "L2.1という状態はありません。", "D3.1という状態はありません。"],
          "5.5", "L1 PM Substates", 770),
        n("int-15", ["", "エラーの報告はERR_COR / ERR_NONFATAL / ERR_FATALのメッセージです。",
                     "割り込みのマスクはMSI-Xのテーブルなどで行います。", "速度の変更はLTSSMのRecoveryです。"],
          "5.3.3", "Power Management Event Mechanisms", 747),

        // 12. 順序規則とエラー処理
        n("ord-1", ["追い越すと、古いデータを読んでしまうことがあります。", "", "同じTCの中の規則です。", "必ず追い越すことはありません。"],
          "2.4.1", "Transaction Ordering Rules for TLPs not using UIO or Flow-Through IDE Streams", 281),
        n("ord-2", ["", "CompletionはPosted Writeを追い越せません（Relaxed Orderingなどの例外を除く）。",
                    "Read RequestはPosted Writeを追い越せません。", "Posted WriteがNon-Postedを追い越すことは許されています。"],
          "2.4.1", "Transaction Ordering Rules for TLPs not using UIO or Flow-Through IDE Streams", 281),
        n("ord-3", ["Correctableはハードウェアが自動で直せるエラーです。", "", "Fatalはリンクの信頼性が失われるエラーです。",
                    "エラーとして扱われます。"],
          "6.2.7", "Error Listing and Rules", 817),
        n("ord-4", ["", "再送で回復できるので、Non-Fatalではありません。", "Fatalではありません。", "エラーとして記録されます。"],
          "6.2.7", "Error Listing and Rules", 817),
        n("ord-5", ["AERはエラーの詳細を記録する仕組みです。", "", "ACSはピアツーピア通信を制御する仕組みです。",
                    "ATSはアドレス変換の仕組みです。"],
          "6.2.11", "Downstream Port Containment (DPC)", 825),
        n("ord-6", ["TCが違うTLP同士には、順序の決まりはありません。", "", "同じ送信元に限った規則ではありません。",
                    "アドレスが同じかどうかには関係なく適用されます。"],
          "2.4.1", "Transaction Ordering Rules for TLPs not using UIO or Flow-Through IDE Streams", 281),
        n("ord-7", ["ROが1なら追い越してよいことになっています。", "", "必ず追い越すわけではありません（許されているだけ）。",
                    "TCが違えばそもそも順序の決まりはありません。"],
          "2.4.1", "Transaction Ordering Rules for TLPs not using UIO or Flow-Through IDE Streams", 281),
        n("ord-8", ["禁止ではありません。", "", "Relaxed Orderingがなくても許されています。", "IDOがなくても許されています。"],
          "2.4.1", "Transaction Ordering Rules for TLPs not using UIO or Flow-Through IDE Streams", 281),
        n("ord-9", ["Correctableではありません。", "Non-Fatalではありません（既定値）。", "", "エラーとして扱われます。"],
          "6.2.7", "Error Listing and Rules", 817),
        n("ord-10", ["", "リンクの速度と幅はLink Statusレジスタにあります。", "DLLPは記録しません。", "MSI-Xのベクタ番号は記録しません。"],
          "7.8.4", "Advanced Error Reporting Extended Capability (AER)", 1336),
        n("ord-11", ["", "Relaxed Orderingがないと追い越せません。", "必ず追い越すことはありません。", "アドレスが違っても追い越せません。"],
          "2.4.1", "Transaction Ordering Rules for TLPs not using UIO or Flow-Through IDE Streams", 281),
        n("ord-12", ["", "帯域のための規則ではありません。", "電力とは関係ありません。", "クレジットとは関係ありません。"],
          "2.4.1", "Transaction Ordering Rules for TLPs not using UIO or Flow-Through IDE Streams", 281),
        n("ord-13", ["", "同じアドレスへの書き込みの順序は緩められません。", "再送の順序はデータリンク層の話です。", "LTSSMとは関係ありません。"],
          "2.4.1", "Transaction Ordering Rules for TLPs not using UIO or Flow-Through IDE Streams", 281),
        n("ord-14", ["", "Completion Timeoutは既定でUncorrectable Non-Fatalです。", "Malformed TLPは既定でUncorrectable Fatalです。",
                     "Unsupported Requestは既定でUncorrectable Non-Fatalです。"],
          "6.2.7", "Error Listing and Rules", 817),
        n("ord-15", ["", "LCRCエラーはデータリンク層で再送されます。", "リンクダウンではCompletionを返せません。",
                     "クレジット不足のときは送信を待つだけです。"],
          "2.3.1", "Request Handling Rules", 266),
        n("ord-16", ["", "Endpointはエラーメッセージを送る側です。", "スイッチのダウンストリームポートは、メッセージを上流へ転送します。",
                     "エラーメッセージは最初の送信元へは戻りません。"],
          "6.2.3", "Error Signaling", 802),
    ]
}
