import Foundation

extension QuizNotes {
    // MARK: - 上級（13〜15章）

    static let latest: [QuizNote] = [
        // 13. 仮想化
        n("virt-1", ["PFはVFを管理する完全な機能で、通常はホストが使います。", "", "RCiEPはRoot Complexに統合されたEndpointです。",
                     "ATCはアドレス変換のキャッシュです。"],
          "9.1", "IOV Architectural Overview", 1713),
        n("virt-2", ["ACSはピアツーピア通信の制御です。", "", "ARIはFunction番号を増やす仕組みです。", "AERはエラーの報告の仕組みです。"],
          "10.1.1", "Address Translation Services (ATS) Overview", 1760),
        n("virt-3", ["", "PASIDはアドレス空間を区別するIDです。", "PRIは、ページを用意してもらうための要求の仕組みです。",
                     "LTRは許容できる遅延を通知する仕組みです。"],
          "6.12", "Access Control Services (ACS)", 888),
        n("virt-4", ["3ビットはARIなしのFunction番号です。", "5ビットはDevice番号です。", "", "16ビットはBDF全体（Routing ID）です。"],
          "6.13", "Alternative Routing-ID Interpretation (ARI)", 900),
        n("virt-5", ["000DhはACSです。", "000EhはARIです。", "000FhはATSです。", ""],
          "9.4.3", "SR-IOV Extended Capability", 1736),
        n("virt-6", ["IOMMUのページテーブルはホスト側にあり、ATCはそのコピーをデバイスが持つものです。", "",
                     "MSI-Xテーブルは割り込みの設定です。", "Retry Bufferは再送用のバッファです。"],
          "10.1.1", "Address Translation Services (ATS) Overview", 1760),
        n("virt-7", ["", "VFの数はSR-IOVの設定で決まります。", "エラーの報告はAERなどの役目です。", "リンク速度とは関係ありません。"],
          "6.20", "PASID", 926),
        n("virt-8", ["0001hはAERです。", "", "001DhはDPCです。", "001EhはL1 PM Substatesです。"],
          "7.7.12", "ACS Extended Capability", 1302),
        n("virt-9", ["", "VFは軽量なFunctionで、PFに管理されます。", "Root Complexは階層の根で、SR-IOVのFunctionではありません。",
                     "ACSはピアツーピアの制御で、Functionではありません。"],
          "9.1", "IOV Architectural Overview", 1713),
        n("virt-10", ["", "レーン数は変わりません。", "転送速度は変わりません。", "消費電力はゼロになりません。"],
          "9.1", "IOV Architectural Overview", 1713),
        n("virt-11", ["", "割り込みを作るのはデバイスです（MSI/MSI-X）。", "リンクの初期化はLTSSMの役目です。",
                      "誤り訂正はFECなどの役目です。"],
          "10.1", "ATS Architectural Overview", 1759),
        n("virt-12", ["", "Endpointは変換を要求する側です。", "スイッチは要求を中継するだけです。", "物理層は関係ありません。"],
          "10.2.2", "Translation Requests", 1770),
        n("virt-13", ["", "FLRはFunctionのリセットです。", "Hot Resetはリンク経由のリセットです。", "PMEは起床を求める仕組みです。"],
          "10.3", "ATS Invalidation", 1787),
        n("virt-14", ["", "Hot Resetはリンクの先全体をリセットします。", "Cold Resetは電源を入れ直すリセットです。",
                      "Link Disableはリンクを止めるだけです。"],
          "6.6.2", "Function Level Reset (FLR)", 852),

        // 14. Gen6
        n("g6-1", ["NRZはGen5までの2値の方式です。", "", "QAM16は無線などで使う変調です。", "PAM3は3値の変調で、PCIeでは使いません。"],
          "4.2.3.1.1", "PAM4 Signaling", 411),
        n("g6-2", ["128バイトはFlitの半分です。", "", "512バイトではありません。", "固定長なのでFECをかけやすくなっています。"],
          "4.2.3.4", "Bytes in Flit Layout", 426),
        n("g6-3", ["FECは誤り訂正で、暗号化ではありません。", "", "レーン数とは関係ありません。", "後方互換のためではありません。"],
          "4.2.3.1.1", "PAM4 Signaling", 411),
        n("g6-4", ["L0sは送信を止める状態で、Flit Modeでは使えません。", "", "L1.2はリンクを止める深い省電力状態です。",
                   "L2はほぼ電源を落とした状態です。"],
          "4.2.6.7", "L0p Overview", 539),
        n("g6-5", ["64 GT/sはGen6です。", "96 GT/sという世代はありません。", "", "256 GT/sはPCIe 8.0の目標です。"],
          "1.2", "PCI Express Link", 148),
        n("g6-6", ["4バイトではありません。", "6バイトはDLPやFECの大きさです。", "", "16バイトではありません。"],
          "4.2.3.4", "Bytes in Flit Layout", 426),
        n("g6-7", ["2バイトではありません。", "", "8バイトはCRCの大きさです。", "12バイトではありません。"],
          "4.2.3.4", "Bytes in Flit Layout", 426),
        n("g6-8", ["128バイトはFlitの前半の大きさです。", "", "242バイトはTLPとDLPを合わせた大きさです。", "256バイトはFlit全体です。"],
          "4.2.3.4", "Bytes in Flit Layout", 426),
        n("g6-9", ["5-Bit Tagは古い仕様の値です。", "8-Bit Tag CompleterはすべてのFunctionに必須です。",
                   "10-Bit Tag Completerは、14-Bit Tagに対応することで自動的に満たされます。", ""],
          "2.2.6", "Transaction Descriptor", 205),
        n("g6-10", ["10⁻⁶はPAM4のFEC前の誤り率（FBER）です。", "10⁻⁹ではありません。", "", "10⁻¹⁵ではありません。"],
          "4.2.3.1.1", "PAM4 Signaling", 411),
        n("g6-11", ["1ビットはNRZです。", "", "4ビットにはPAM16が必要です。", "8ビットではありません。"],
          "4.2.3.1.1", "PAM4 Signaling", 411),
        n("g6-12", ["2レベルはNRZです。", "3レベルはPAM3です。", "", "8レベルはPAM8です。"],
          "4.2.3.1.1", "PAM4 Signaling", 411),
        n("g6-13", ["", "Flit ModeではTLPごとのシーケンス番号はありません。", "バイト単位ではありません。",
                    "Flit ModeではAckとNakはDLLPではありません。"],
          "4.2.3.4.2.1", "Flit Sequence Number and Retry Mechanism", 433),
        n("g6-14", ["", "誤りを含んだまま受け取ることはありません。", "再送で回復できるので、Detectまで戻りません。",
                    "ECRCは誤りを検出するだけで、訂正はできません。"],
          "4.2.3.4.2.1", "Flit Sequence Number and Retry Mechanism", 433),
        n("g6-15", ["約32 GB/sはGen4 x16です。", "約64 GB/sはGen5 x16です。", "", "約256 GB/sはGen7 x16です。"],
          "1.2", "PCI Express Link", 148),
        n("g6-16", ["", "Ack/Nak DLLPを使うのはNon-Flit Modeです。", "Ordered Setでは伝えません。", "Message TLPでは伝えません。"],
          "4.2.3.4", "Bytes in Flit Layout", 426),

        // 15. PCIe 7.0
        n("p7-1", ["", "Flit Modeは6.0で導入されました。", "PAM4は6.0で導入されました。", "L0pは6.0で導入されました。"],
          "改版履歴", "Revision History（7.0 Version 1.0）", 87),
        n("p7-2", ["2.5 GT/sから直接128.0 GT/sのイコライゼーションはできません。", "32.0 GT/sから始められるのは64.0 GT/sのイコライゼーションです。", "",
                   "128.0 GT/sで動作中にやり直すことはできません。"],
          "4.2.4", "Link Equalization Procedure for 8.0 GT/s and Higher Data Rates", 479),
        n("p7-3", ["0110bは64.0 GT/sです。", "0111bは予約です。", "", "1111bではありません。"],
          "7.5.3.8", "Link Status Register (Offset 12h)", 1173),
        n("p7-4", ["0026hは16.0 GT/s用です。", "002Ahは32.0 GT/s用です。", "0031hは64.0 GT/s用です。", ""],
          "7.7.8", "Physical Layer 128.0 GT/s Extended Capability", 1260),
        n("p7-5", ["2個ではありません。", "", "8個は00b、または共通の最高速度が128.0 GT/s未満のときです。", "上限があります。"],
          "3.3", "Data Link Feature Exchange", 338),
        n("p7-6", ["DFEは1タップだけです（64.0 GT/sまでは16タップのDFE）。", "", "プリコーディングは送信側の符号変換で、等化ではありません。",
                   "FECは誤り訂正で、等化ではありません。"],
          "8.4.1", "Receiver Stressed Eye Specification", 1627),
        n("p7-7", ["3タップ（プレカーソル1）は8.0〜32.0 GT/sの送信FIRです。", "", "2タップではありません。",
                   "29タップは受信側の参照FFEです。"],
          "8.3.3", "Tx Voltage Parameters", 1579),
        n("p7-8", ["0〜-6 dBではありません。", "", "0〜-30 dBではありません。", "DCゲインは調整できます。"],
          "8.4.1", "Receiver Stressed Eye Specification", 1627),
        n("p7-9", ["1ではありません（DFEが1タップ）。", "2は送信FIRのプレカーソルの数です。", "", "24はポストカーソルの数です。"],
          "8.4.2", "Stressed Eye Test", 1648),
        n("p7-10", ["EQ TS2は、8.0 GT/sに切り替える前（2.5 / 5.0 GT/s）に送るものです。", "128b/130b EQ TS2は、64.0 GT/sまでのイコライゼーションで使います。", "",
                    "SKPはクロックの差を吸収するOrdered Setです。"],
          "4.2.5.1", "Training Sequences", 494),
        n("p7-11", ["128.0 GT/s Status Registerには、パリティエラーの記録はありません。", "", "AERのHeader LogはTLPのヘッダを記録します。",
                    "Link Statusは速度や幅などの状態です。"],
          "7.7.5", "Physical Layer 16.0 GT/s Extended Capability", 1237),
        n("p7-12", ["64.0 GT/sはbit 5です。", "", "Flit Modeの対応は別のフィールドで示します。", "予約ではありません。"],
          "7.5.3.18", "Link Capabilities 2 Register (Offset 2Ch)", 1196),
        n("p7-13", ["NRZは32.0 GT/sまでです。", "", "PAM8は使いません。", "QAM16は使いません。"],
          "1.2", "PCI Express Link", 148),
        n("p7-14", ["64 GB/sはGen5 x16です。", "128 GB/sはGen6 x16です。", "", "512 GB/sは双方向の合計です。"],
          "1.2", "PCI Express Link", 148),
        n("p7-15", ["", "PAM8は使いません。", "レーン数は変わりません。", "128b/130bには戻していません（1b/1bのまま）。"],
          "1.2", "PCI Express Link", 148),
        n("p7-16", ["2022年はPCIe 6.0が発表された年です。", "", "2028年はPCIe 8.0の目標です。", "2019年はPCIe 5.0の年です。"],
          "改版履歴", "Revision History（7.0 Version 1.0）", 87),
        n("p7-17", ["", "フロッピーディスクとは関係ありません。", "キーボードやマウスには帯域が大きすぎます。",
                    "オーディオ専用機器には帯域が大きすぎます。"],
          "1.1", "An Evolving I/O Interconnect", 147),
        n("p7-18", ["", "後方互換性があるので接続できます。", "Gen1に固定されることはありません。", "故障しません。"],
          "4.2.5.10", "Link Data Rate Negotiation", 534),
    ]
}
