import Foundation

extension QuizNotes {
    // MARK: - 中級（5〜8章）

    static let intermediate: [QuizNote] = [
        // 5. TLP
        n("tlp-1", ["Memory Readは応答（CplD）が返るNon-Postedです。", "", "Configuration WriteはCplが返るNon-Postedです。",
                    "I/O WriteはCplが返るNon-Postedです。"],
          "2.1.1", "Address Spaces, Transaction Types, and Usage", 161),
        n("tlp-2", ["データのないTLPはFmtで「データなし」を示します。Length=0は0バイトではありません。", "1DWはLength=1のときです。", "",
                    "Length=0は正しい値（1024DW）です。"],
          "2.2.1", "Common Packet Header Fields", 165),
        n("tlp-3", ["3DWは32ビットアドレスのときです。", "", "5DWのヘッダはNon-Flit Modeにはありません。", "8DWではありません。"],
          "2.2.1", "Common Packet Header Fields", 165),
        n("tlp-4", ["TCとAttrは優先度と順序の属性で、対応付けには使いません。", "", "Byte Enableは有効なバイトを示すだけです。",
                    "Completionはアドレスではなく、IDでルーティングされます。"],
          "2.2.6", "Transaction Descriptor", 205),
        n("tlp-5", ["", "そのような名前のステータスはありません。", "そのような名前のステータスはありません。", "そのような名前のステータスはありません。"],
          "2.2.9", "Completion Rules", 252),
        n("tlp-6", ["1KBではありません。", "", "64KBではありません。", "4KB境界の制約があります。"],
          "2.2.7", "Memory, I/O, and Configuration Request Rules", 216),
        n("tlp-7", ["000bです。", "001bです。", "", "TLP PrefixはFmt=100bです。"],
          "2.2.1", "Common Packet Header Fields", 165),
        n("tlp-8", ["アドレスルーティングはメモリやI/Oのリクエストです。", "", "ブロードキャストは一部のMessageです。",
                    "暗黙のルーティングはMessageで使います。"],
          "2.2.4", "Routing and Addressing Rules", 195),
        n("tlp-9", ["0バイトではありません。", "1バイトは000000000001bです。", "4095は12ビットの最大値ですが、0は4096を表します。", ""],
          "2.2.9", "Completion Rules", 252),
        n("tlp-10", ["SCは000bです。", "URは001bです。", "RRSは010bです。", ""],
          "2.2.9", "Completion Rules", 252),
        n("tlp-11", ["ECRCが付いていることを示すのはTDビットです。", "", "優先度はTC（Traffic Class）で示します。",
                     "ヘッダの長さはFmtで示します。"],
          "2.7.2", "Error Forwarding (Data Poisoning)", 326),
        n("tlp-12", ["", "4DWは4GB以上のアドレスのときだけ使います。", "4GB未満では3DWと決まっています。",
                     "Max Payload Sizeはヘッダの形式とは関係ありません。"],
          "2.2.4", "Routing and Addressing Rules", 195),
        n("tlp-13", ["Cplはデータのない応答です（Writeの完了やエラーの通知）。", "", "CplLkはロック付きの読み出しへの応答です。",
                     "MsgDはデータ付きのMessageで、応答ではありません。"],
          "2.2.9", "Completion Rules", 252),
        n("tlp-14", ["バイト単位ではありません。端数はByte Enableで指定します。", "", "16バイトはデータクレジットの単位です。",
                     "64バイトではありません。"],
          "2.2.1", "Common Packet Header Fields", 165),
        n("tlp-15", ["", "最後のDWの有効バイトはLast DW BEです。", "宛先はアドレスやIDで示します。", "優先度はTCで示します。"],
          "2.2.5", "First/Last DW Byte Enables Rules", 202),
        n("tlp-16", ["", "アドレスはAddressフィールドです。", "TagはRequester IDとは別のフィールドです。", "TCは別のフィールドです。"],
          "2.2.6", "Transaction Descriptor", 205),
        n("tlp-17", ["", "1回のReadで要求できる最大サイズはMax_Read_Request_Sizeです。", "クレジットの上限は受信側が通知する値です。",
                     "ヘッダのサイズは形式（3DW/4DWなど）で決まります。"],
          "2.2.2", "TLPs with Data Payloads - Rules", 191),
        n("tlp-18", ["1回で読めるのは512バイトまでです。", "2回では1KBしか読めません。", "", "8回は必要ありません。"],
          "2.2.7", "Memory, I/O, and Configuration Request Rules", 216),

        // 6. データリンク層
        n("dll-1", ["8ビットではありません。", "10ビットはTagの拡張などの長さです。", "", "16ビットではありません。"],
          "3.6.2", "LCRC, TLP Sequence Number, and Retry Management (TLP Transmitter)", 361),
        n("dll-2", ["エラーのTLPだけを選んで再送する方式（Selective Repeat）ではありません。", "",
                    "NAKだけでリンクはリセットしません。", "NAKを受けたら必ず再送します。"],
          "3.6.2", "LCRC, TLP Sequence Number, and Retry Management (TLP Transmitter)", 361),
        n("dll-3", ["TLPは捨てずに、再トレーニングのあとも再送を続けます。", "",
                    "システム全体はリセットされません。", "速度が自動でGen1に固定されることはありません。"],
          "3.6.2", "LCRC, TLP Sequence Number, and Retry Management (TLP Transmitter)", 361),
        n("dll-4", ["タイマによる再送で回復できます。", "", "受信側はそもそもTLPを正しく受けているので、NAKは送りません。",
                    "物理層はTLPを作りません。再送はデータリンク層のリプレイバッファから行います。"],
          "3.6.2", "LCRC, TLP Sequence Number, and Retry Management (TLP Transmitter)", 361),
        n("dll-5", ["8ビットではありません。", "16ビットはDLLPのCRCです。", "", "64ビットではありません。"],
          "3.6.2", "LCRC, TLP Sequence Number, and Retry Management (TLP Transmitter)", 361),
        n("dll-6", ["次に期待する番号（NEXT_RCV_SEQ）から1を引いた値が入ります。", "", "エラーのTLPの番号ではなく、その手前の正しく受けた番号です。",
                    "送信側の番号ではありません。"],
          "3.6.3", "LCRC and TLP Sequence Number (TLP Receiver) (Non-Flit Mode)", 371),
        n("dll-7", ["受信バッファは受信側にあります。", "", "フロー制御はクレジットの管理で、再送用のバッファではありません。",
                    "MSI-Xテーブルは割り込みの設定です。"],
          "3.6.2", "LCRC, TLP Sequence Number, and Retry Management (TLP Transmitter)", 361),
        n("dll-8", ["DL_Inactiveはリンクが使えない状態です。", "DL_Featureは機能を交換している途中です。",
                    "DL_Initはフロー制御を初期化している途中です。", ""],
          "3.2", "Data Link Control and Management State Machine", 334),
        n("dll-9", ["1ずつではありません。", "", "4ずつではありません。", "8ずつではありません（3ビットのカウンタです）。"],
          "3.6.2", "LCRC, TLP Sequence Number, and Retry Management (TLP Transmitter)", 361),
        n("dll-10", ["", "MSI-Xは割り込みの機能で、コンフィグ空間で設定します。", "ECRCはトランザクション層の機能です。",
                     "SR-IOVはコンフィグ空間で設定する機能です。"],
          "3.3", "Data Link Feature Exchange", 338),
        n("dll-11", ["", "Completionが返らないのは、トランザクション層のCompletion Timeoutです。",
                     "クレジット不足のときは送信を待つだけです。", "速度変更は物理層の仕事です。"],
          "3.6.3", "LCRC and TLP Sequence Number (TLP Receiver) (Non-Flit Mode)", 371),
        n("dll-12", ["", "ACKは省略できません（返さないと送信側がタイマで再送します）。", "送信側はACKを使ってバッファを解放します。",
                     "Non-Flit ModeではACKはDLLPです。"],
          "3.6.3", "LCRC and TLP Sequence Number (TLP Receiver) (Non-Flit Mode)", 371),
        n("dll-13", ["0〜255は8ビットです。", "", "0〜65535は16ビットです。", "番号は0から始まります。"],
          "3.6.2", "LCRC, TLP Sequence Number, and Retry Management (TLP Transmitter)", 361),
        n("dll-14", ["", "重複はエラーではないので、NAKは返しません。", "二重に処理されないよう、重複分は捨てます。",
                     "重複だけでリンクはリセットしません。"],
          "3.6.3", "LCRC and TLP Sequence Number (TLP Receiver) (Non-Flit Mode)", 371),
        n("dll-15", ["4バイトはCRCを除いた本体の長さです。", "", "8バイトはフレーミング記号（SDP・END）を含めた長さです。", "16バイトではありません。"],
          "3.5", "Data Link Layer Packets (DLLPs)", 349),
        n("dll-16", ["", "通常どおり通信できるのはDL_Activeです。", "省電力はリンクの状態（L1など）で表します。",
                     "エラーからの回復は物理層のRecoveryです。"],
          "3.2", "Data Link Control and Management State Machine", 334),

        // 7. フロー制御
        n("fc-1", ["4バイトは1DWです。", "", "64バイトではありません。", "256バイトではありません。"],
          "2.6.1", "Flow Control (FC) Rules", 298),
        n("fc-2", ["", "256÷16＝16なので、PDは16です。", "Memory WriteはPostedなので、NPではなくPのクレジットを使います。",
                   "ヘッダは1つ、データが16です。"],
          "2.6.1", "Flow Control (FC) Rules", 298),
        n("fc-3", ["送信禁止を意味する値ではありません。", "", "あとから通知する意味ではありません。", "エラーではありません。"],
          "2.6.1", "Flow Control (FC) Rules", 298),
        n("fc-4", ["", "クレジット待ちでむしろ遅れることもあります。", "CRCは別に必要です。", "リンク幅とは関係ありません。"],
          "2.6", "Ordering and Receive Buffer Flow Control", 297),
        n("fc-5", ["2種類ではありません。", "3種類（Posted・Non-Posted・Completion）×2（ヘッダ・データ）です。", "", "8種類ではありません。"],
          "2.6.1", "Flow Control (FC) Rules", 298),
        n("fc-6", ["", "データを運ばないので、NPDは使いません。", "Memory ReadはPostedではありません。", "CplHは応答を返す側が使います。"],
          "2.6.1", "Flow Control (FC) Rules", 298),
        n("fc-7", ["InitFC1は初期化のときだけ使います。", "InitFC2も初期化のときだけ使います。", "", "AckはTLPの受信確認です。"],
          "3.5", "Data Link Layer Packets (DLLPs)", 349),
        n("fc-8", ["すべてのポートに必須ではありません。", "8.0 GT/sでは必須ではありません。", "",
                   "Flit Modeを使うときも必須ですが、Flit Modeに限らず16.0 GT/s以上に対応するポートは必須です。"],
          "3.3", "Data Link Feature Exchange", 338),
        n("fc-9", ["", "10ビットではありません。", "12ビットはDataFCです。", "16ビットではありません。"],
          "3.4.2", "Scaled Flow Control", 349),
        n("fc-10", ["1クレジットは16バイトです。", "", "16は256バイトのときです。", "64はバイト数で、クレジットの数ではありません。"],
          "2.6.1", "Flow Control (FC) Rules", 298),
        n("fc-11", ["", "16バイトはデータクレジット1単位です。", "4バイトではありません。", "1DWではありません。"],
          "2.6.1", "Flow Control (FC) Rules", 298),
        n("fc-12", ["", "Read/Writeではなく、応答が要るかどうかで分けます。", "アドレス空間の種類では分けません。",
                    "TCはVCへの対応付けに使います。"],
          "2.6.1", "Flow Control (FC) Rules", 298),
        n("fc-13", ["", "クレジット方式は、送る前に空きを確かめる仕組みです。", "捨てません。待つだけです。",
                    "クレジット不足は異常ではないので、再トレーニングはしません。"],
          "2.6.1", "Flow Control (FC) Rules", 298),
        n("fc-14", ["", "種別ごとに独立しているので送れます。", "Relaxed Orderingは順序の属性で、クレジットとは関係ありません。",
                    "破棄されません。"],
          "2.6.1", "Flow Control (FC) Rules", 298),
        n("fc-15", ["", "デバイス全体で1つではありません。", "Tagはリクエストの識別番号です。", "レーンごとではありません。"],
          "2.6.1", "Flow Control (FC) Rules", 298),
        n("fc-16", ["6では96バイトしか送れません。端数は切り上げます。", "", "25は4バイト単位で数えたときの値です。",
                    "100はバイト数です。"],
          "2.6.1", "Flow Control (FC) Rules", 298),

        // 8. 物理層
        n("phy-1", ["TS1はリンクトレーニングに使います。", "", "EIOSはElectrical Idleに入る合図です。",
                    "FTSはL0sから戻るときに使います。"],
          "4.2.8", "Clock Tolerance Compensation", 638),
        n("phy-2", ["Data Blockは10bです。", "", "エラーを示す値ではありません（00bと11bは不正）。", "アイドルを示す値ではありません。"],
          "4.2.2.1", "Lane Level Encoding", 388),
        n("phy-3", ["スクランブルは誰でも元に戻せるので、暗号ではありません。", "誤りは訂正できません。",
                    "", "データ量は減りません。"],
          "4.2.2.4", "Scrambling in Non-Flit Mode and Flit Mode", 399),
        n("phy-4", ["25 MHzではありません。", "", "125 MHzではありません。", "250 MHzではありません。"],
          "8.6", "Refclk Specifications", 1699),
        n("phy-5", ["8次ではありません。", "", "23次は128b/130bのLFSRです。", "32次ではありません。"],
          "4.2.1.3", "Data Scrambling", 386),
        n("phy-6", ["16次は8b/10bのLFSRです。", "", "31次ではありません。", "64次ではありません。"],
          "4.2.2.4", "Scrambling in Non-Flit Mode and Flit Mode", 399),
        n("phy-7", ["", "EIEOSはElectrical Idleから抜けるときに使います。", "SKPはクロックの差を吸収します。",
                    "SDSはデータストリームの開始を示します。"],
          "4.2.5.3", "Electrical Idle Sequences (EIOS and EIEOS)", 522),
        n("phy-8", ["4つではありません。", "8つではありません。", "", "16個ではありません。"],
          "4.2.4.2", "Encoding of Presets", 492),
        n("phy-9", ["レーン反転は、レーン番号の並びの逆転を吸収する機能です。", "", "デスキューはレーン間の到着時間のずれを補正します。",
                    "スクランブルはビット列をランダム化します。"],
          "4.2.5.5", "Lane Polarity Inversion", 530),
        n("phy-10", ["1シンボルのSTPは8b/10b（2.5 / 5.0 GT/s）のときです。", "", "SDPトークンはDLLPの先頭に付けます。",
                     "128b/130bにENDはありません（長さで終わりを判断）。"],
          "4.2.2.3.1", "Framing Tokens in Non-Flit Mode", 390),
        n("phy-11", ["", "8b/10bは誤りを訂正できません。", "スクランブルとは別の仕組みです。", "電源管理とは関係ありません。"],
          "4.2.1.1", "Symbol Encoding", 379),
        n("phy-12", ["", "FECは誤り訂正で、Gen6からです。", "PAM4は変調方式です。", "ECRCはTLPのCRCです。"],
          "4.2.1.1", "Symbol Encoding", 379),
        n("phy-13", ["", "イコライゼーションは波形の劣化を補正します。", "スクランブルはビット列をランダム化します。",
                     "ディエンファシスは送信波形の調整です。"],
          "4.2.5.12", "Lane-to-Lane De-skew", 536),
        n("phy-14", ["", "消費電力を増やすのが目的ではありません。", "符号化効率とは関係ありません。", "クロックは作りません。"],
          "4.2.4.1", "Rules for Transmitter Coefficients", 491),
        n("phy-15", ["", "Polarity Inversionは差動ペアの＋−の入れ替えを吸収します。",
                     "Lane Marginingは受信の余裕を測る機能です。", "Scramblingはビット列のランダム化です。"],
          "4.2.5.11", "Link Width and Lane Sequence Negotiation", 535),
        n("phy-16", ["", "Lane Reversalはレーン番号の逆転を吸収する機能です。", "ASPMはリンクの省電力の仕組みです。",
                     "ECRCはTLPのCRCです。"],
          "4.2.18", "Lane Margining at Receiver", 662),
    ]
}
